plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = 'eureka-server.jar'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}
